services:
  api:
    build:
      target: dev
    volumes:
      - ./src/api/PirateChess.Api:/app/src/api/PirateChess.Api
      - ./src/lib/piratechess_lib:/app/src/lib/piratechess_lib
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    entrypoint: ["dotnet", "watch", "run", "--project", "/app/src/api/PirateChess.Api"]

