// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PirateChess.Api.Data;

#nullable disable

namespace PirateChess.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PirateChess.Api.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.CachedCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChessableBid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestResponseJson")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CachedCourses");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.ChessableCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EncryptedBearer")
                        .HasColumnType("longtext");

                    b.Property<string>("EncryptedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("longtext");

                    b.Property<bool>("UseBearer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ChessableCredentials");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.ExportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterCount")
                        .HasColumnType("int");

                    b.Property<string>("ChessableBid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LineCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingMode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExportHistories");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.GeneratedPgn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CachedCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PgnContent")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("TrainingMode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CachedCourseId");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedPgns");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.CachedCourse", b =>
                {
                    b.HasOne("PirateChess.Api.Models.Entities.AppUser", "User")
                        .WithMany("CachedCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.ChessableCredential", b =>
                {
                    b.HasOne("PirateChess.Api.Models.Entities.AppUser", "User")
                        .WithMany("ChessableCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.ExportHistory", b =>
                {
                    b.HasOne("PirateChess.Api.Models.Entities.AppUser", "User")
                        .WithMany("ExportHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.GeneratedPgn", b =>
                {
                    b.HasOne("PirateChess.Api.Models.Entities.CachedCourse", "CachedCourse")
                        .WithMany("GeneratedPgns")
                        .HasForeignKey("CachedCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PirateChess.Api.Models.Entities.AppUser", "User")
                        .WithMany("GeneratedPgns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CachedCourse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.AppUser", b =>
                {
                    b.Navigation("CachedCourses");

                    b.Navigation("ChessableCredentials");

                    b.Navigation("ExportHistories");

                    b.Navigation("GeneratedPgns");
                });

            modelBuilder.Entity("PirateChess.Api.Models.Entities.CachedCourse", b =>
                {
                    b.Navigation("GeneratedPgns");
                });
#pragma warning restore 612, 618
        }
    }
}
